title: Khoirun Niswatin # your name (or website title) here
logo: "/images/khoir200.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, you can call me Khoir 
  <br><br>
  <a href="https://www.instagram.com/khoirunniswatin_/">Take a Look at My Instagram Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
